#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
rustup toolchain install nightly --allow-downgrade
# cargo install --version="~0.6" sqlx-cli --no-default-features --features rustls,postgres
cargo fetch
cargo check
cargo build
