#!/usr/bin/env bash

# Check first argument for "cov", "cover", "coverage", etc.
if [[ "${1:0:3}" == "cov" ]]; then
    # NOTE: does a clean build, so takes longer
    cargo tarpaulin
else
    cargo test
fi
